require: rubocop-ordered_methods

AllCops:
  TargetRubyVersion: 3.1

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Layout/OrderedMethods:
  Include:
    - 'lib/frigate_rb/endpoints.rb' 
  EnforcedStyle: alphabetical
